### ISSUE TITLE
Can't start the server

### ISSUE THREAD

**Issue by marvk** [Hagmar/autoplace#1]
```
Traceback (most recent call last):
  File "place_server.py", line 118, in <module>
    main()
  File "place_server.py", line 99, in main
    server.run(args)
  File "place_server.py", line 32, in run
    self.projects[pid] = new_project
NameError: name 'pid' is not defined

```

python 3.6 on debian

**Comment by Hagmar** [comment]
Oops, I completely missed this! Fixed now :)
