### ISSUE TITLE
Can't start the Server

### ISSUE THREAD

**Issue by marvk** [Hagmar/autoplace#2]
```
Error: could not identify image file type
Traceback (most recent call last):
  File "place_server.py", line 118, in <module>
    main()
  File "place_server.py", line 99, in main
    server.run(args)
  File "place_server.py", line 31, in run
    args.y, args.project_name)
  File "/home/place/autoplace/project.py", line 29, in __init__
    self.parse_image(image)
  File "/home/place/autoplace/project.py", line 35, in parse_image
    self.target = self.map_colors(data)
  File "/home/place/autoplace/project.py", line 50, in map_colors
    for x, pixel in enumerate(row):
TypeError: 'numpy.float64' object is not iterable

```

Debian/Python3.6 as before. Dependencies should be installed correctly...

**Comment by Hagmar** [comment]
Hmm... What image format are you using? And what is the resolution of the picture?

**Comment by marvk** [comment]
17x5 and png

**Comment by Hagmar** [comment]
Did you update after the recent PR? I'm unable to reproduce your error, could you upload your image somewhere and link it here?

**Comment by marvk** [comment]
Nvm, I removed the image file by accident. It just didn't exist.

**Comment by Hagmar** [comment]
Haha alright
